function h = setup_camera_gui(h)
    % Last edited July 19, 2024
    
    %% Parameters
    h.pixelSize     = h.camera.pixelCalibration;
    h.bitdepth      = get(h.camObj, 'BitDepth') ;

    %% Figure
    h.figure=figure(...             
        'PaperPositionMode','auto',...
        'Toolbar','figure',...
        'Menubar', 'none',...
        'NumberTitle','Off',...
        'Name', append('IBIS Viewer. ', h.camera.Tag),...
        'unit','pixels',...
        'Position',[100,100,200+h.vidRes(1)/h.divisor+125,280+h.vidRes(2)/h.divisor]...
        );




    %% Image Axes
    corner = [50,100];
    h.axes = axes('Units','pixels',...
                'Tag', 'MainImageView',...
                'PositionConstraint', 'InnerPosition',...
                'Position',[corner(1),corner(2),h.vidRes(1)/h.divisor,h.vidRes(2)/h.divisor]);
    h.X_worldLimit  = h.pixelSize*h.vidRes(1)/2 * [-1, 1];
    h.Y_worldLimit  = h.pixelSize*h.vidRes(2)/2 * [-1, 1];
    
    h.RA = imref2d([h.vidRes(2), h.vidRes(1)],h.X_worldLimit,h.Y_worldLimit);

    h.Image = imshow(2^h.bitdepth*ones(h.vidRes(2), h.vidRes(1), h.nBands),...
                    h.RA,'Parent',h.axes);
    h.Image.YData=-1*h.Image.YData;
    set(h.axes,'YDir','normal','XAxisLocation','Top','YAxisLocation','Right');
    
    %--Create profile axes
    axis_size=100;
    pos = get(h.axes,'Position');
    posRt= [pos(1)+pos(3)+20, pos(2)          , axis_size   , pos(4)];
    posTop=[pos(1)          , pos(2)+pos(4)+20, pos(3), axis_size];

    %--Create marker counter
    h.markerX = double.empty;
    h.markerY = double.empty;
    h.markerCounter = 0;
    h.marker = images.roi.Point.empty;
    
    h.axesRt =axes('Units','pixels',...
                'PositionConstraint', 'InnerPosition',...
                'Position',posRt,...
                'Units','pixels',...
                'NextPlot','add',...
                'YAxisLocation','Right');
    
    h.axesTop=axes('Units','pixels',...
                'PositionConstraint', 'InnerPosition',...
                'Position',posTop,...
                'NextPlot','add',...
                'Units','pixels',...
                'XAxisLocation','Top');


%% -- Camera Label 
    info = strcat(h.camera.Tag, '   RMS:  x=0  y=0');
    h.camLbl = uicontrol(h.figure,...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', [10,750,720,50],...
        'String', info,...
        'FontSize', 24);


            
%% -- Camera controls and labels
    i = 0;  
    h.CamCtlPanel = uipanel(h.figure,'Title','Camera Properties',...
            'Units','pixels',...
            'Position',[(posRt(1)+posRt(3)+25), corner(2)-120, 120, 230]);
    i=i+1;  
    h.CamCtrl.shutter=uicontrol(h.CamCtlPanel,'Style','edit',...
        'Units', 'Characters',...
        'Position',[1,i*2,8,1.5],...  % [Left, Bottomm Width, Height]
        'Tag','Shutter');
    
     h.CamCtrl.l_shutter=uicontrol(h.CamCtlPanel,'Style','text',...
        'Units', 'Characters',...
        'Position',[10,i*2,8,1.5],...
        'Tag','Lbl_Shutter',...
        'String','Shutter');

     i=i+1;
     h.CamCtrl.trg_delay=uicontrol(h.CamCtlPanel,'Style','edit',...
        'Units', 'Characters',...
        'Position',[1,i*2,8,1.5],...
        'Tag','TriggerDelay',...
        'Enable', 'on', ...
        'Value',get(h.camObj, 'Gain'));

    
     h.CamCtrl.l_trg_delay=uicontrol(h.CamCtlPanel,'Style','text',...
        'Units', 'Characters',...
        'Position',[10,i*2,8,1.5],...
        'Tag','Lbl_TirggerDelay',...
       'String','Delay');

    
    i = i+1;
    h.CamCtrl.autoGain = uicontrol(h.CamCtlPanel,'Style','togglebutton',...
                'Tag','autoGain',...
                'String','autoGain',...
                'Units','Characters',...
                'Position',[1,i*2,20,2]);

    
    i=i+1;

    h.CamCtrl.gainsl = uicontrol(h.CamCtlPanel, Style="slider", ...
        Units="characters", ...
        Position=[1,i*2,20,1.5], ...
        Tag="GainSlider", ...
        Value=0, ...
        Min=0,Max=24);



     i=i+1;   
     h.CamCtrl.gain=uicontrol(h.CamCtlPanel,'Style','edit',...
        'Units', 'Characters',...
        'Position',[1,i*2,8,1.5],...
         'Tag','GainEdit',...
        'Value',0);


     h.CamCtrl.l_gain=uicontrol(h.CamCtlPanel,'Style','text',...
        'Units', 'Characters',...
        'Position',[10,i*2,10,1.5],...
        'Tag','Lbl_Gain',...
        'String','Gain');
    i=i+1;
    h.CamCtrl.BlackLevel=uicontrol(h.CamCtlPanel,'Style','edit',...
        'Units', 'Characters',...
        'Position',[1,i*2,8,1.5],...
        'Tag','BlackLevel',...
        'Value',get(h.camObj, 'Gain'));

    
     h.CamCtrl.l_blackLevel=uicontrol(h.CamCtlPanel,'Style','text',...
        'Units', 'Characters',...
        'Position',[10,i*2,8,1.5],...
        'Tag','Lbl_BlackLevel',...
        'String','BlckLvl');

     i=i+1;
     h.CamCtrl.Threshold=uicontrol(h.CamCtlPanel,'Style','edit',...
        'Units', 'Characters',...
        'Position',[1,i*2,8,1.5],...
        'Tag','Threshold',...
        'Enable', 'off', ...
        'Value',get(h.camObj, 'Gain'));

    
     h.CamCtrl.l_blackLevel=uicontrol(h.CamCtlPanel,'Style','text',...
        'Units', 'Characters',...
        'Position',[10,i*2,8,1.5],...
        'Tag','Lbl_Threshold',...
       'String','Thrshld');



    
    %% --Interaction Panel buttons
    B.nv = 10;
    BtnPositions=zeros(4,B.nv);
        %button sizes are normalized to their parent panel.
    for i=0:B.nv
        BtnPositions(:,i+1) = [0.05, 0.025+0.98*i/B.nv ,0.95, 0.95/B.nv ];
    end
    i=1;
    
    h.ButtonPanel = uipanel(h.figure,'Title','Interaction Panel',...
                    'Units','pixels',...
                    'Position', [(posRt(1)+posRt(3)+25), corner(2)+120, 120, posRt(4)-70]);
            
    h.frameCtr= uicontrol(h.ButtonPanel,'Style','text',...
                    'Tag','frameCounter',...
                    'String','0',...
                    'Units','normalized',...
                    'Position',BtnPositions(:,i));
        i=i+1;

    h.AutoSave = uicontrol(h.ButtonPanel,'Style','togglebutton',...
                'Tag','AutoSave',...
                'String','AutoSave OFF',...
                'Units','normalized',...
                'Position',BtnPositions(:,i));


        i=i+1;
    h.saveImage = uicontrol(h.ButtonPanel,'Style','pushbutton',...
                    'Tag','takeImage',...
                    'String','Save Raw Image',...
                    'Units','normalized',...
                    'Position',BtnPositions(:,i));


        i=i+1;
    h.marker= uicontrol(h.ButtonPanel,'Style','pushbutton',...
                    'Tag','SetMarker',...
                    'String','SetMarker',...
                    'Units','normalized',...
                    'Position',BtnPositions(:,i));  






    %    i=i+1;
    % h.rect= uicontrol(h.ButtonPanel,'Style','pushbutton',...
    %                'Tag','ManualCenter',...
    %                'String','Manual Center',...
    %                'Units','normalized',...
    %                'Position',BtnPositions(:,i));





        i=i+1;
    h.GetBgnd=uicontrol(h.ButtonPanel,'Style','pushbutton',...
                    'Tag','Take Bkgd',...
                    'String','getBackground',...
                    'Units','normalized',...
                    'Position',BtnPositions(:,i));


    
        i=i+1;
    h.SubtBgnd=uicontrol(h.ButtonPanel,'Style','togglebutton',...
                    'Tag','SubtBgnd',...
                    'String','Subtract Background',...
                    'Units','normalized',...
                    'Position',BtnPositions(:,i));



        i=i+1;  
    h.AvgImages=uicontrol(h.ButtonPanel,'Style','togglebutton',...
                    'Tag','AverageImages',...
                    'String','Average Images',...
                    'Units','normalized',...
                    'Position',BtnPositions(:,i));



        i=i+1;  
    h.Pause=uicontrol(h.ButtonPanel,'Style','togglebutton',...
                    'Tag','Pause',...
                    'String','Pause Acquisition',...
                    'Units','normalized',...
                    'Position',BtnPositions(:,i), ...
                    BackgroundColor='green');
        i=i+1;



    h.LEDswitch = uicontrol(h.ButtonPanel,'Style','togglebutton',...
                    'Tag','LEDswitch',...
                    'String','LED on/off',...
                    'Units','normalized',...
                    'Position',BtnPositions(:,i));

         i=i+1;
        
    h.RunMode = uicontrol(h.ButtonPanel,'Style','togglebutton',...
                'Tag','RunMode',...
                'String','Hardware trg',...
                'Units','normalized',...
                'Position',BtnPositions(:,i), BackgroundColor='green');
  

%% Filter Wheel 
    h.IFW.group = uibuttongroup(h.figure,'Title','Filter wheel',...
            'Units','pixels',...
            'SelectionChangedFcn',{@IFW_position},...
            'Position',[pos(1)+pos(3)+20, pos(2)+pos(4)+20, axis_size, 1.3*axis_size]);


    h.IFW.p1=uicontrol(h.IFW.group,'Style','radiobutton',...
        'Units', 'Characters',...
        'Position',[0,6.5,18,1.5],...
        'String','Clear');

    h.IFW.p2=uicontrol(h.IFW.group,'Style','radiobutton',...
        'Units', 'Characters',...
        'Position',[0,5,18,1.5],...
        'String','Trans 50 %');

    h.IFW.p3=uicontrol(h.IFW.group,'Style','radiobutton',...
        'Units', 'Characters',...
        'Position',[0,3.5,18,1.5],...
        'String','Trans 10 %');
    
    h.IFW.p4=uicontrol(h.IFW.group,'Style','radiobutton',...
        'Units', 'Characters',...
        'Position',[0,2,18,1.5],...
        'String','Trans 1 %');

    h.IFW.p5=uicontrol(h.IFW.group,'Style','radiobutton',...
        'Units', 'Characters',...
        'Position',[0,0.5,18,1.5],...
        'String','540 nm BP');
    
    

    %% Profile Center controls and labels
    h.ProfCtlPanel = uipanel(h.figure,'Title','Profile Properties',...
            'Units','pixels',...
            'Position',[posRt(1)+posRt(3)+25, pos(2)+pos(4)+50, 120, 1.3*axis_size]);

    butBot=0.2;
    butHt=1.5;
    
% Display the Centroid
    h.ProfCtrl.X=uicontrol(h.ProfCtlPanel,'Style','edit',...
        'Units', 'Characters',...
        'Position',[0,butBot,7.5,butHt],...  % [Left, Bottom, Width, Height]
        'Tag','ProfPosX',...
        'String','0');
        
    h.ProfCtrl.Y=uicontrol(h.ProfCtlPanel,'Style','edit',...
        'Units', 'Characters',...
        'Position',[8,butBot,7.5,butHt],...  % [Left, Bottom, Width, Height]
        'Tag','ProfPosY',...
        'String','0');
    
     h.ProfCtrl.posLbl=uicontrol(h.ProfCtlPanel,'Style','text',...
            'Units', 'Characters',...
            'Position',[15,butBot,9,butHt],...
            'Tag','Lbl_position',...
            'String','Center');
        butBot=butBot+butHt+0.0;

% Display stdDev values
    h.ProfCtrl.Xsize=uicontrol(h.ProfCtlPanel,'Style','text',...
        'Units', 'Characters',...
        'Position',[0,butBot,7,butHt],...  % [Left, Bottom, Width, Height]
        'Tag','ProfPosX',...
        'String','-');
        
    h.ProfCtrl.Ysize=uicontrol(h.ProfCtlPanel,'Style','text',...
        'Units', 'Characters',...
        'Position',[8,butBot,7,butHt],...  % [Left, Bottom, Width, Height]
        'Tag','ProfPosY',...
        'String','-');
    
     h.ProfCtrl.sizeLbl=uicontrol(h.ProfCtlPanel,'Style','text',...
            'Units', 'Characters',...
            'Position',[16,butBot,7,butHt],...
            'Tag','Lbl_position',...
            'String','σ (x,y)');
        butBot=butBot+butHt+0.2;
        
%layout the profile center buttons in a panel
    h.profCtrl.group = uibuttongroup(h.ProfCtlPanel,...
        'Units', 'Characters',...
        'Position',[0,butBot,19,5],...
        'Tag','ProfGroup');




    h.ProfCtrl.manual=uicontrol(h.profCtrl.group,'Style','radiobutton',...
        'Units', 'Characters',...
        'Position',[0,0,18,1.5],...
        'String','Manual');
    
    h.ProfCtrl.auto=uicontrol(h.profCtrl.group,'Style','radiobutton',...
        'Units', 'Characters',...
        'Position',[0,1.5,18,1.5],...
        'String','Auto Once');

    h.ProfCtrl.track=uicontrol(h.profCtrl.group,'Style','radiobutton',...
        'Units', 'Characters',...
        'Position',[0,3,18,1.5],...
        'String','Track');
            
    %% Set graph limits
    h.plotRt=plot(h.axesRt,1:h.vidRes(2),-h.pixelSize*(-h.vidRes(2)/2:(h.vidRes(2)/2-1)));
    set(h.axesRt,'YDir','reverse')
    xlim(h.axesRt,[0,2^h.bitdepth-1])
    ylim(h.axesRt,h.pixelSize*[-h.vidRes(2)/2,h.vidRes(2)/2]);
    xlim manual
    ylim manual
    
    h.plotTop=plot(h.axesTop,h.pixelSize*(-h.vidRes(1)/2:h.vidRes(1)/2-1), 1:1:h.vidRes(1));
    xlim(h.axesTop,h.pixelSize*[-h.vidRes(1)/2,h.vidRes(1)/2-1])
    ylim(h.axesTop,[0,2^h.bitdepth-1]);
    xlim manual
    ylim manual

    set(h.axes,'FontSizeMode','manual','FontSize',8)
        % place ROI dot to show profile center
    x0= str2double(h.ProfCtrl.X.String);
    y0= str2double(h.ProfCtrl.Y.String);
    h.roi=images.roi.Crosshair(h.axes, 'Position',[x0, y0],...
                'Deletable', 0,...
                'InteractionsAllowed','none',...
                'Color','g', LabelAlpha=0.1, LineWidth=1, Visible='on');
   
    h.Image.CDataMapping='direct';
%     set(h.figure,'CurrentAxes',h.axes)
    

    % setting a custom version of "jet" color map with black color at 0 and
    % white at 1
    cmap = jet(2^h.bitdepth-1);
    colormap(h.axes, cmap);

    h.cbar = colorbar(h.axes,'Location','manual',...
                        'Units','pixels','Position',[30,100,15,pos(4)],...
                        'FontSize',8);
    

    %% Define Callback Functions
    % Link h to h.figure so struct can be passed to (and edited) in callback
    guidata(h.figure, h); 
    set(h.figure,               'CloseRequestFcn', @GUI_CloseRequest_Callback);
    set(h.CamCtrl.shutter,      'Callback', @GUI_Shutter_Callback);
    set(h.CamCtrl.Threshold,    'Callback', @GUI_Threshold_Callback);
    set(h.AutoSave,             'Callback', @GUI_AutoSave_Callback);
    set(h.saveImage,            'Callback', @GUI_saveImage_Callback);
    set(h.marker,               'Callback', @GUI_MakeMarker_Callback);
    set(h.CamCtrl.autoGain,     'Callback', @GUI_autoGain_Callback);
    set(h.CamCtrl.gainsl,       'Callback', @GUI_Gain_Callback);
    set(h.CamCtrl.gain,         'Callback', @GUI_Gain_Callback);
    set(h.CamCtrl.BlackLevel,   'Callback', @GUI_BlackLevel_Callback);
    set(h.CamCtrl.trg_delay,    'Callback', @GUI_TriggerDelay_Callback);
%     set(h.rect,                 'Callback', @GUI__rectImage_Callback);
    set(h.GetBgnd,              'Callback', @GUI_TakeBgnd_Callback);
    set(h.SubtBgnd,             'Callback', @GUI_SubtBgnd_Callback);
    set(h.AvgImages,            'Callback', @GUI_AvgImageToggle_Callback);
    set(h.Pause,                'Callback', @GUI_PauseAcq_Callback);
    set(h.RunMode,              'Callback', @GUI_RunMode_Callback);
    set(h.LEDswitch,            'Callback', @GUI_LEDswitch_Callback);


    set(h.profCtrl.group,       'SelectionChangedFcn', @GUI_proftype);
    set(h.IFW.group,            'SelectionChangedFcn', @GUI_IFW_position);



 end  
