function h = MainGui()
    datetime.setDefaultFormats('defaultdate','yyyy-MM-dd');
    buttonCount=7;
    % imaqmex('feature', '-gigeDisablePacketResend', true);
    h.figure=figure(...             % first create the figure so that the handle can be passed to the m-file
        'PaperPositionMode','auto',...
        'Toolbar','none',...
        'Menubar', 'none',...
        'NumberTitle','Off',...
        'Units','Characters',...
        'Name','PM Selector',...
        'CloseRequestFcn',{@CloseRequest_Callback}...
        );
%         'Position',[25,5,8,5*1.5],...

    % Build up individual buttons for each station
    parent_handle=h.figure;

    h.PM_n=cameraListTest;      % Call helper script to find all cameras

    BtnPositions=zeros(4,buttonCount);
        %button sizes are normalized to their parent panel.
    for i=(buttonCount-1):-1:0
        BtnPositions(:,i+1) = [0.02, 0.025+0.98*i/buttonCount ,0.95, 0.95/buttonCount ];
    end

    % i=1;

    for i=1:buttonCount
        h.PM_n.h(i) = uicontrol(parent_handle,'Style','togglebutton',...
                    'String',h.PM_n.Tag{i},...
                    'Callback',{@PM_Callback},...
                    'Units','normalized',...
                    'Position',BtnPositions(:,i));
    end
 
%%     h.PM_n.Tag{i}=["PM" num2str(i)];
%    h.PM_n.h(i) = uicontrol(parent_handle,'Style','togglebutton',...
%                    'String',h.PM_n.Tag{i},...
%                    'Callback',{@PM_Callback},...
%                    'Units','normalized',...
%                    'Position',BtnPositions(:,i));
%
%    i=i+1;

%%     h.PM_n.Tag(i)=['PM' num2str(i)];
%    h.PM_n.h(i)= uicontrol(parent_handle,'Style','pushbutton',...
%                    'String',h.PM_n.Tag{i},...
%                    'Callback',{@PM_Callback},...
%                    'Units','normalized',...
%                    'Position',BtnPositions(:,i));
%    i=i+1;

%%     h.PM_n.Tag(i)=['PM' num2str(i)];
%    h.PM_n.h(i)= uicontrol(parent_handle,'Style','pushbutton',...
%                    'String',h.PM_n.Tag{i},...
%                    'Callback',{@PM_Callback},...
%                    'String',h.PM_n.Tag{i},...
%                    'Units','normalized',...
%                    'Position',BtnPositions(:,i));
%    i=i+1;

%%     h.PM_n.Tag(i)=['PM' num2str(i)];
%    h.PM_n.h(i)= uicontrol(parent_handle,'Style','pushbutton',...
%                    'String',h.PM_n.Tag{i},...
%                    'Callback',{@PM_Callback},...
%                    'String',h.PM_n.Tag{i},...
%                    'Units','normalized',...
%                    'Position',BtnPositions(:,i));
%    i=i+1;
%%     h.PM_n.Tag(i)=['PM' num2str(i)];
%    h.PM_n.h(i)= uicontrol(parent_handle,'Style','pushbutton',...
%                    'String',h.PM_n.Tag{i},...
%                    'Callback',{@PM_Callback},...
%                    'String',h.PM_n.Tag{i},...
%                    'Units','normalized',...
%                    'Position',BtnPositions(:,i));

    function CloseRequest_Callback(~,~)
        %called when the figure is closed. Will likely close all of the
        %cameras and serial connections
        delete(h.figure)
        
    end

    function PM_Callback(source, eventID)
        %this function would call the GUI refering to the PM_number passed
        %IBIS_4(PM_number)
        %IFW(PM_number)
        if source.Value
            j=find(strcmp(eventID.Source.String,h.PM_n.Tag));
            IBIS_5(h.PM_n.n(j), ...
                h.PM_n.pixelCalibration(j), ...
                h.PM_n.h(j), ...
                h.PM_n.Tag{j}, ...
                h.PM_n.SN{j}, ...
                h.PM_n.flip_v(j), h.PM_n.flip_h(j));
            source.Enable='off';
            % disp(h.PM_n.n(j));
            % IFW(h.PM_n.n(j))
        else
            f = msgbox('This Screen is already activated.');    
        end
    end
end