
h.f = figure;
h.numberOfClicks = 0; 
guidata(h.f,h)
button_increase = uicontrol(h.f,...
            'Style','togglebutton',...
            'String','Increase',...
            'Units','normalized',...
            'Position',[0.1, 0.1, 0.3, 0.3]);

button_print = uicontrol(h.f,...
            'Style','togglebutton',...
            'String','Print',...
            'Units','normalized',...
            'Position',[0.4, 0.1, 0.3, 0.3]);

set(button_increase, 'Callback', @increase_callback);
set(button_print, 'Callback', @print_callback);
